services:
  db-emadkala:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    network_mode: host
    volumes:
      - ./Database/mysql:/var/lib/mysql
  
  aspnet-emadkala:
    image: aspnet-emadkala
    depends_on:
      - db-emadkala
      - mail-emadkala
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
